name: pmp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - mpi4py
  - mpich
  - matplotlib
  - pip
  - pip:
      - numpy<2.0
      - meep>=1.25.0
      - autograd
      - nlopt
