name: pmp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - meep
  - mpi4py
  - mpich
  - matplotlib  # For waveguide plotting
  - pip
  - pip:
      - autograd
      - nlopt
      - numpy<2.0
